{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "AUTOMART API",
    "description": "# Auto-Mart\r\nAuto Mart is an online marketplace for automobiles of diverse makes, model or body type. With Auto Mart, users can sell their cars or buy from trusted dealerships or private sellers.\r\n\r\n### Build status\r\n[![Build Status](https://travis-ci.org/NonsoAmadi10/Auto-Mart.svg?branch=develop)](https://travis-ci.org/NonsoAmadi10/Auto-Mart)\r\n[![Coverage Status](https://coveralls.io/repos/github/NonsoAmadi10/Auto-Mart/badge.svg?branch=develop)](https://coveralls.io/github/NonsoAmadi10/Auto-Mart?branch=develop)\r\n[![Maintainability](https://api.codeclimate.com/v1/badges/7cd8c9394ca4e3c2039c/maintainability)](https://codeclimate.com/github/NonsoAmadi10/Auto-Mart/maintainability)\r\n[![Test Coverage](https://api.codeclimate.com/v1/badges/7cd8c9394ca4e3c2039c/test_coverage)](https://codeclimate.com/github/NonsoAmadi10/Auto-Mart/test_coverage)\r\n\r\n\r\n### Required Features\r\n1. User can sign up.\r\n2. User can sign in.\r\n3. User (seller) can post a car sale advertisement.\r\n4. User (buyer) can make a purchase order.\r\n5. User (buyer) can update the price of his/her purchase order.\r\n6. User (seller) can mark his/her posted AD as sold.\r\n7. User (seller) can update the price of his/her posted AD.\r\n8. User can view a specific car.\r\n9. User can view all unsold cars.\r\n10. User can view all unsold cars within a price range.\r\n11. Admin can delete a posted AD record.\r\n12. Admin can view all posted ads whether sold or unsold.\r\n\r\n### Extra Feature\r\n- User can report a car advert\r\n  \r\n\r\n### Useful Links\r\n\r\n- This project is being managed with  [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/2346959)\r\n- The UI templates are hosted here [Github pages](https://nonsoamadi10.github.io/Auto-Mart/)\r\n- The API URL has been succesfully deployed to heroku. It can be accessed [here](https://automart-api-2019.herokuapp.com)\r\n\r\n\r\n### Technologies \r\n- [NodeJS](https://nodejs.org) A run time environment based off Chrome's v8 Engines for writing Javascript server-side applications.\r\n \r\n- [Express](https://expressjs.com) Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.\r\n  \r\n- [ES Lint](https://eslint.org) A pluggable and configurable linter tool for identifying and reporting on patterns in JavaScript. Maintain your code quality with ease.\r\n\r\n- [Babel](https://babeljs.io) Babel is a JavaScript compiler. Babel is a toolchain that is mainly used to convert ECMAScript 2015+ code into a backwards compatible version of JavaScript in current and older browsers or environments. \r\n\r\n#### Tools\r\n- [Postman](https://getpostman.com) Postman is the only complete API development environment, and flexibly integrates with the software development cycle.\r\n- [Swagger](https://swagger.io) Swagger aides in development across the entire API lifecycle, from design and documentation, to test and deployment. \r\n- **Testing**\r\n    - [Mocha](https://mochajs.org) Mocha is a feature-rich JavaScript test framework running on Node.js and in the browser, making asynchronous testing simple and fun. \r\n    - [Chai](https://chaijs.com) Chai is a BDD / TDD assertion library for [node](http://nodejs.org) and the browser that can be delightfully paired with any javascript testing framework.\r\n- [Heroku](https://heroku.com) is a platform as a service (PaaS) that enables developers to build, run, and operate applications entirely in the cloud.\r\n- [Cloudinary](https://cloudinary.com) is a cloud-based image and video management solution. It enables users to upload, store, manage, manipulate and deliver images and video for websites and apps.\r\n- [Travis CI](https://travis-ci.org)  is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub.\r\n- [Coveralls](https://coveralls.io) Coveralls is a hosted analysis tool, providing statistics about your code coverage. \r\n- [CodeClimate](https://codeclimate.com) provides automated code review for test coverage, maintainability and more so that you can save time and merge with confidence.\r\n\r\n\r\n### Installations\r\n ##### Getting Started\r\n - You need to have [node](https://nodejs.org) installed on your system \r\n - You need to have a [cloudinary](https://cloudinary.com) account in order to get an API secret as well as an API key.\r\n  \r\n ##### Clone \r\n - To clone this repo, you need to open a command line terminal and run : `  git clone https://github.com/NonsoAmadi10/Auto-Mart.git `\r\n\r\n##### Install\r\n- Install all depencies used in this project by running ` npm install `\r\n\r\n- Set the following environment variables in your .env file:\r\n\r\n  - PORT - An Integer specifying the PORT your application will run on.\r\n  - JWT_SECRET - A random string used for generation authorization tokens.\r\n  - CLOUDINARY_NAME => [your name on cloudinary](https://cloudinary.com)\r\n  - CLOUDINARY_API_KEY=> [your cloudinary_ secret key](https://cloudinary.com)\r\n  - CLOUDINARY_API_SECRET=> [your cloudinary secret](https://cloudinary.com)\r\n\r\n\r\n### Starting the server locally\r\n- Run ` npm run dev-start ` to start the server\r\n\r\n#### Testing App with Postman\r\n- Open postman \r\n- Test with api endpoints found [here](https://automart-api-2019.herokuapp.com/api-docs)\r\n##### Testing with mocha and chai\r\n- ``` Run npm test ``` to see test pass locally\r\n\r\n\r\n### Author \r\n- Amadi Justice Chinonso\r\n\r\n### Acknowledgement\r\n- I learned how to use swagger using this [resource](https://itnext.io/setting-up-swagger-in-a-node-js-application-d3c4d7aa56d4)\r\n- I learned how to upload to cloudinary using this [article](https://medium.com/@joeokpus/uploading-images-to-cloudinary-using-multer-and-expressjs-f0b9a4e14c54)\r\n  \r\n",
    "contact": {}
  },
  "host": "automart-api-2019.herokuapp.com",
  "basePath": "/api/v1",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/car": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Post Car Advert",
        "tags": [
          "Cars  Request"
        ],
        "operationId": "CarPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "manufacturer",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "photo",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "model",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "price",
            "in": "formData",
            "required": true,
            "type": "number",
            "format": "double",
            "description": "Price must be a float"
          },
          {
            "name": "bodyType",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": "It Can be Car, truck or Van"
          },
          {
            "name": "state",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": "New Or Used"
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/PostCarAdvert"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "status": "success",
                "data": {
                  "id": 7,
                  "owner_id": 6,
                  "owner_email": "Cherrpie@aol.com",
                  "created_on": "2019-07-09T14:47:50Z",
                  "state": "new",
                  "status": "available",
                  "price": "2000000.00",
                  "manufacturer": "toyota",
                  "model": "camry",
                  "body_type": "car",
                  "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683669/ilotemlwl4tmzsecqgyf.jpg",
                  "flagged": false
                }
              }
            },
            "headers": {
              "Server": {
                "type": "string",
                "default": "Cowboy"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*"
              },
              "Content-Length": {
                "type": "string",
                "default": "350"
              },
              "Etag": {
                "type": "string",
                "default": "W/\"15e-Dcqv8zxRbfGSdhajyeDgGzkFt0Q\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 09 Jul 2019 14:47:51 GMT"
              },
              "Via": {
                "type": "string",
                "default": "1.1 vegur"
              }
            }
          }
        },
        "security": []
      }
    },
    "/car/7/status": {
      "patch": {
        "description": "TODO: Add Description",
        "summary": "Update Car status",
        "tags": [
          "Cars  Request"
        ],
        "operationId": "Car7StatusPatch",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateCarstatusRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateCarstatus"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "status": "success",
                "data": {
                  "id": 7,
                  "owner_id": 6,
                  "owner_email": "Cherrpie@aol.com",
                  "created_on": "2019-07-09T14:47:50Z",
                  "state": "new",
                  "status": "sold",
                  "price": "2000000.00",
                  "manufacturer": "toyota",
                  "model": "camry",
                  "body_type": "car",
                  "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683669/ilotemlwl4tmzsecqgyf.jpg",
                  "flagged": false
                }
              }
            },
            "headers": {
              "Server": {
                "type": "string",
                "default": "Cowboy"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*"
              },
              "Content-Length": {
                "type": "string",
                "default": "345"
              },
              "Etag": {
                "type": "string",
                "default": "W/\"159-ZooNLbEOWL014fYEBRcrQ6DkdDI\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 09 Jul 2019 14:51:22 GMT"
              },
              "Via": {
                "type": "string",
                "default": "1.1 vegur"
              }
            }
          }
        },
        "security": []
      }
    },
    "/car/8/price": {
      "patch": {
        "description": "Allows a User to exist the price of an unsold vehicle",
        "summary": "Update Car Price",
        "tags": [
          "Cars  Request"
        ],
        "operationId": "Car8PricePatch",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateCarPriceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateCarPrice"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "status": "success",
                "data": {
                  "id": 8,
                  "owner_id": 6,
                  "owner_email": "Cherrpie@aol.com",
                  "created_on": "2019-07-09T14:53:08Z",
                  "state": "new",
                  "status": "available",
                  "price": "700000.00",
                  "manufacturer": "toyota",
                  "model": "camry",
                  "body_type": "car",
                  "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683988/egwmjfljbs7wmzwcbofn.jpg",
                  "flagged": false
                }
              }
            },
            "headers": {
              "Server": {
                "type": "string",
                "default": "Cowboy"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*"
              },
              "Content-Length": {
                "type": "string",
                "default": "349"
              },
              "Etag": {
                "type": "string",
                "default": "W/\"15d-2Jma3QvcxmCo/pK/8ctJzrdxGK8\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 09 Jul 2019 15:04:16 GMT"
              },
              "Via": {
                "type": "string",
                "default": "1.1 vegur"
              }
            }
          }
        },
        "security": []
      }
    },
    "/": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Search for all unsold cars",
        "tags": [
          "Cars  Request"
        ],
        "operationId": "UnnammedEndpointGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Searchforallunsoldcars"
            },
            "examples": {
              "application/json": {
                "status": "error",
                "error": "You must be logged in to use this route"
              }
            }
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "description": "User Can Create an Account",
        "summary": "User Should be able to signin",
        "tags": [
          "Misc"
        ],
        "operationId": "AuthSigninPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UserShouldbeabletosigninRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/UserShouldbeabletosignin"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "status": "success",
                "data": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZmlyc3RfbmFtZSI6IkNoaW5vbnNvIiwibGFzdF9uYW1lIjoiQW1hZGkiLCJlbWFpbCI6IkNoZXJycGllQGFvbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRtNHd6OU4zVzhoSy5uTFVRR0JzeG9PaS5ua3dkN0Z3WEEzSWZkVUg0YkVySDJJTzhvc1pCSyIsImFkZHJlc3MiOiI3NCwgZXBpYyB0b3dlciwgQ2hpY2FnbyIsImlzX2FkbWluIjoiZiIsImlhdCI6MTU2MjY4MzAyMH0.TTJmLAX7ufN36kIRRyEL8MM5c3jEsNfNBOp6OPaum6s",
                  "id": 6,
                  "email": "Cherrpie@aol.com",
                  "last_name": "Amadi",
                  "first_name": "Chinonso",
                  "is_admin": "f"
                }
              }
            },
            "headers": {
              "Server": {
                "type": "string",
                "default": "Cowboy"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*"
              },
              "Content-Length": {
                "type": "string",
                "default": "509"
              },
              "Etag": {
                "type": "string",
                "default": "W/\"1fd-zlxEvwVa6ns3vPQ8eUuVsQt1+FE\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 09 Jul 2019 14:37:00 GMT"
              },
              "Via": {
                "type": "string",
                "default": "1.1 vegur"
              }
            }
          }
        }
      }
    },
    "/auth/signup": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "User should be able to signup",
        "tags": [
          "Misc"
        ],
        "operationId": "AuthSignupPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UsershouldbeabletosignupRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Usershouldbeabletosignup"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "status": "success",
                "data": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZmlyc3RfbmFtZSI6IkpheWNlZSIsImxhc3RfbmFtZSI6InRvbHVsb3BlIiwiZW1haWwiOiJOb25ueXB5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDZxS2YwU3BjcXpSeTQ5dUZ1MEU3dHVsMUZDYU1tSU9jYTlmb0FHclVUQm8xWHdtREZOQy9pIiwiYWRkcmVzcyI6IjcxLCBRdWVlbnMgUm9hZCwgT2tsYWhvbWEiLCJpc19hZG1pbiI6InQiLCJpYXQiOjE1NjI2ODMzMTd9.Gh-K6bjWU2sE52Rqfo6853RI4uQZph2-Cg5Kb7zITxo",
                  "id": 7,
                  "first_name": "Jaycee",
                  "last_name": "tolulope",
                  "email": "Nonnypy@gmail.com",
                  "address": "71, Queens Road, Oklahoma"
                }
              }
            },
            "headers": {
              "Server": {
                "type": "string",
                "default": "Cowboy"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Access-Control-Allow-Origin": {
                "type": "string",
                "default": "*"
              },
              "Content-Length": {
                "type": "string",
                "default": "539"
              },
              "Etag": {
                "type": "string",
                "default": "W/\"21b-N7NlFSfwr+95l4JqjKADxsjLs9Y\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 09 Jul 2019 14:41:57 GMT"
              },
              "Via": {
                "type": "string",
                "default": "1.1 vegur"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PostCarAdvert": {
      "title": "PostCarAdvert",
      "example": {
        "status": "success",
        "data": {
          "id": 7,
          "owner_id": 6,
          "owner_email": "Cherrpie@aol.com",
          "created_on": "2019-07-09T14:47:50Z",
          "state": "new",
          "status": "available",
          "price": "2000000.00",
          "manufacturer": "toyota",
          "model": "camry",
          "body_type": "car",
          "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683669/ilotemlwl4tmzsecqgyf.jpg",
          "flagged": false
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data": {
      "title": "Data",
      "example": {
        "id": 7,
        "owner_id": 6,
        "owner_email": "Cherrpie@aol.com",
        "created_on": "2019-07-09T14:47:50Z",
        "state": "new",
        "status": "available",
        "price": "2000000.00",
        "manufacturer": "toyota",
        "model": "camry",
        "body_type": "car",
        "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683669/ilotemlwl4tmzsecqgyf.jpg",
        "flagged": false
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "owner_id": {
          "type": "integer",
          "format": "int32"
        },
        "owner_email": {
          "type": "string"
        },
        "created_on": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "price": {
          "type": "string"
        },
        "manufacturer": {
          "type": "string"
        },
        "model": {
          "type": "string"
        },
        "body_type": {
          "type": "string"
        },
        "image_url": {
          "type": "string"
        },
        "flagged": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "owner_id",
        "owner_email",
        "created_on",
        "state",
        "status",
        "price",
        "manufacturer",
        "model",
        "body_type",
        "image_url",
        "flagged"
      ]
    },
    "UpdateCarstatusRequest": {
      "title": "UpdateCarstatusRequest",
      "example": {
        "status": "sold"
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      },
      "required": [
        "status"
      ]
    },
    "UpdateCarstatus": {
      "title": "UpdateCarstatus",
      "example": {
        "status": "success",
        "data": {
          "id": 7,
          "owner_id": 6,
          "owner_email": "Cherrpie@aol.com",
          "created_on": "2019-07-09T14:47:50Z",
          "state": "new",
          "status": "sold",
          "price": "2000000.00",
          "manufacturer": "toyota",
          "model": "camry",
          "body_type": "car",
          "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683669/ilotemlwl4tmzsecqgyf.jpg",
          "flagged": false
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "UpdateCarPriceRequest": {
      "title": "UpdateCarPriceRequest",
      "example": {
        "price": 700000.0
      },
      "type": "object",
      "properties": {
        "price": {
          "type": "number",
          "format": "double"
        }
      },
      "required": [
        "price"
      ]
    },
    "UpdateCarPrice": {
      "title": "UpdateCarPrice",
      "example": {
        "status": "success",
        "data": {
          "id": 8,
          "owner_id": 6,
          "owner_email": "Cherrpie@aol.com",
          "created_on": "2019-07-09T14:53:08Z",
          "state": "new",
          "status": "available",
          "price": "700000.00",
          "manufacturer": "toyota",
          "model": "camry",
          "body_type": "car",
          "image_url": "http://res.cloudinary.com/nonnypy/image/upload/v1562683988/egwmjfljbs7wmzwcbofn.jpg",
          "flagged": false
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Searchforallunsoldcars": {
      "title": "Searchforallunsoldcars",
      "example": {
        "status": "error",
        "error": "You must be logged in to use this route"
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "error": {
          "type": "string"
        }
      },
      "required": [
        "status",
        "error"
      ]
    },
    "UserShouldbeabletosigninRequest": {
      "title": "UserShouldbeabletosigninRequest",
      "example": {
        "email": "Cherrpie@aol.com",
        "password": "Jonbellion"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "UserShouldbeabletosignin": {
      "title": "UserShouldbeabletosignin",
      "example": {
        "status": "success",
        "data": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZmlyc3RfbmFtZSI6IkNoaW5vbnNvIiwibGFzdF9uYW1lIjoiQW1hZGkiLCJlbWFpbCI6IkNoZXJycGllQGFvbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRtNHd6OU4zVzhoSy5uTFVRR0JzeG9PaS5ua3dkN0Z3WEEzSWZkVUg0YkVySDJJTzhvc1pCSyIsImFkZHJlc3MiOiI3NCwgZXBpYyB0b3dlciwgQ2hpY2FnbyIsImlzX2FkbWluIjoiZiIsImlhdCI6MTU2MjY4MzAyMH0.TTJmLAX7ufN36kIRRyEL8MM5c3jEsNfNBOp6OPaum6s",
          "id": 6,
          "email": "Cherrpie@aol.com",
          "last_name": "Amadi",
          "first_name": "Chinonso",
          "is_admin": "f"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data3"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data3": {
      "title": "Data3",
      "example": {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZmlyc3RfbmFtZSI6IkNoaW5vbnNvIiwibGFzdF9uYW1lIjoiQW1hZGkiLCJlbWFpbCI6IkNoZXJycGllQGFvbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRtNHd6OU4zVzhoSy5uTFVRR0JzeG9PaS5ua3dkN0Z3WEEzSWZkVUg0YkVySDJJTzhvc1pCSyIsImFkZHJlc3MiOiI3NCwgZXBpYyB0b3dlciwgQ2hpY2FnbyIsImlzX2FkbWluIjoiZiIsImlhdCI6MTU2MjY4MzAyMH0.TTJmLAX7ufN36kIRRyEL8MM5c3jEsNfNBOp6OPaum6s",
        "id": 6,
        "email": "Cherrpie@aol.com",
        "last_name": "Amadi",
        "first_name": "Chinonso",
        "is_admin": "f"
      },
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "email": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "is_admin": {
          "type": "string"
        }
      },
      "required": [
        "token",
        "id",
        "email",
        "last_name",
        "first_name",
        "is_admin"
      ]
    },
    "UsershouldbeabletosignupRequest": {
      "title": "UsershouldbeabletosignupRequest",
      "example": {
        "firstname": "Jaycee",
        "lastname": "tolulope",
        "email": "Nonnypy@gmail.com",
        "address": "71, Queens Road, Oklahoma",
        "password": "245,nayusabi",
        "confirmPassword": "245,nayusabi",
        "adminSecret": "andela"
      },
      "type": "object",
      "properties": {
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        },
        "adminSecret": {
          "type": "string"
        }
      },
      "required": [
        "firstname",
        "lastname",
        "email",
        "address",
        "password",
        "confirmPassword",
        "adminSecret"
      ]
    },
    "Usershouldbeabletosignup": {
      "title": "Usershouldbeabletosignup",
      "example": {
        "status": "success",
        "data": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZmlyc3RfbmFtZSI6IkpheWNlZSIsImxhc3RfbmFtZSI6InRvbHVsb3BlIiwiZW1haWwiOiJOb25ueXB5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDZxS2YwU3BjcXpSeTQ5dUZ1MEU3dHVsMUZDYU1tSU9jYTlmb0FHclVUQm8xWHdtREZOQy9pIiwiYWRkcmVzcyI6IjcxLCBRdWVlbnMgUm9hZCwgT2tsYWhvbWEiLCJpc19hZG1pbiI6InQiLCJpYXQiOjE1NjI2ODMzMTd9.Gh-K6bjWU2sE52Rqfo6853RI4uQZph2-Cg5Kb7zITxo",
          "id": 7,
          "first_name": "Jaycee",
          "last_name": "tolulope",
          "email": "Nonnypy@gmail.com",
          "address": "71, Queens Road, Oklahoma"
        }
      },
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data4"
        }
      },
      "required": [
        "status",
        "data"
      ]
    },
    "Data4": {
      "title": "Data4",
      "example": {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZmlyc3RfbmFtZSI6IkpheWNlZSIsImxhc3RfbmFtZSI6InRvbHVsb3BlIiwiZW1haWwiOiJOb25ueXB5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDZxS2YwU3BjcXpSeTQ5dUZ1MEU3dHVsMUZDYU1tSU9jYTlmb0FHclVUQm8xWHdtREZOQy9pIiwiYWRkcmVzcyI6IjcxLCBRdWVlbnMgUm9hZCwgT2tsYWhvbWEiLCJpc19hZG1pbiI6InQiLCJpYXQiOjE1NjI2ODMzMTd9.Gh-K6bjWU2sE52Rqfo6853RI4uQZph2-Cg5Kb7zITxo",
        "id": 7,
        "first_name": "Jaycee",
        "last_name": "tolulope",
        "email": "Nonnypy@gmail.com",
        "address": "71, Queens Road, Oklahoma"
      },
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      },
      "required": [
        "token",
        "id",
        "first_name",
        "last_name",
        "email",
        "address"
      ]
    }
  },
  "tags": [
    {
      "name": "Cars  Request"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}